### Save new user
POST http://localhost:8888/create
Content-Type: application/json
Accept: application/json

{
  "firstname": "Ivan",
  "lastname": "Ivanov",
  "patronymic": "Ivanovich",
  "birthday": "1992-11-12",
  "numberOfChildren": 8,
  "gender": "MALE"
}


### Get user's list.
GET http://localhost:8888/



